# Redis configuration

# Network
bind 0.0.0.0
protected-mode no
port 6379

# Persistence
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Append Only File
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Logging
loglevel notice

# Performance
tcp-backlog 511
timeout 0
tcp-keepalive 300
