#!/usr/bin/env python3
"""
Generate static HTML mockups for accountant review.
- Dashboard
- Account hierarchy
- Transaction list
- Individual transaction details
- Workflows summary
- Rules review
"""

import json
import sys
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, List
import csv

# ============================================================================
# Configuration
# ============================================================================

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; padding: 20px; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; margin-bottom: 10px; font-size: 24px; }}
        h2 {{ color: #555; margin-top: 20px; margin-bottom: 10px; font-size: 18px; border-bottom: 2px solid #007acc; padding-bottom: 5px; }}
        h3 {{ color: #666; margin-top: 15px; margin-bottom: 8px; font-size: 14px; }}
        .meta {{ color: #999; font-size: 12px; margin-bottom: 15px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        thead {{ background: #f0f0f0; }}
        th {{ text-align: left; padding: 10px; font-weight: 600; border-bottom: 2px solid #ddd; font-size: 12px; }}
        td {{ padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 13px; }}
        tr:hover {{ background: #f9f9f9; }}
        .debit {{ color: #27ae60; font-weight: 500; }}
        .credit {{ color: #c0392b; font-weight: 500; }}
        .info {{ background: #e7f3ff; padding: 10px; border-left: 4px solid #007acc; margin: 10px 0; }}
        .warning {{ background: #fff3cd; padding: 10px; border-left: 4px solid #ffc107; margin: 10px 0; }}
        .success {{ background: #d4edda; padding: 10px; border-left: 4px solid #28a745; margin: 10px 0; }}
        .posting-block {{ background: #f9f9f9; padding: 10px; border: 1px solid #ddd; margin: 10px 0; }}
        .posting-line {{ display: flex; justify-content: space-between; padding: 5px 0; font-size: 12px; }}
        .posting-line.total {{ border-top: 1px solid #ddd; font-weight: 600; }}
        .nav {{ margin-bottom: 20px; }}
        .nav a {{ display: inline-block; margin-right: 15px; padding: 8px 12px; background: #007acc; color: white; text-decoration: none; border-radius: 3px; font-size: 12px; }}
        .nav a:hover {{ background: #005a9c; }}
        .impact-tree {{ margin-left: 20px; font-size: 12px; }}
        .account-row {{ padding: 5px 0; }}
        .parent-account {{ font-weight: 600; color: #333; }}
        .sub-account {{ color: #666; margin-left: 20px; }}
        .root-account {{ font-weight: 700; color: #000; background: #f0f0f0; padding: 5px; }}
        footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 11px; }}
    </style>
</head>
<body>
    <div class="container">
        {content}
    </div>
    <footer>Generated by QB Rule Mining Pipeline | {timestamp}</footer>
</body>
</html>
"""

class HTMLRenderer:
    """Generate static HTML for accountant review."""

    def __init__(self, run_dir: Path):
        self.run_dir = run_dir
        self.html_dir = run_dir / "html"
        self.data_dir = run_dir / "normalized_data"
        self.rules_dir = run_dir / "posting_rules"
        self.workflows_dir = run_dir / "workflows"

        self.accounts = {}
        self.account_hierarchy = {}
        self.transactions = {}
        self.impacts = []
        self.rules = []
        self.workflows = []

        self.html_dir.mkdir(parents=True, exist_ok=True)

    def load_data(self):
        """Load normalized data."""
        logger.info("Loading data for HTML rendering...")

        # Accounts
        accounts_file = self.data_dir / "accounts.csv"
        if accounts_file.exists():
            with open(accounts_file) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    self.accounts[row['account_id']] = row
                    self.account_hierarchy[row['account_id']] = {
                        'parent_id': row['parent_account_id'],
                        'root_id': row['root_account_id'],
                        'name': row['account_name'],
                        'fqn': row['fully_qualified_name'],
                        'depth': int(row['depth'])
                    }

        # Transactions
        txn_file = self.data_dir / "transactions.csv"
        if txn_file.exists():
            with open(txn_file) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    self.transactions[row['txn_id']] = row

        # Impacts
        impacts_file = self.data_dir / "account_impacts.csv"
        if impacts_file.exists():
            with open(impacts_file) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    row['debit_amount'] = float(row['debit_amount'] or 0)
                    row['credit_amount'] = float(row['credit_amount'] or 0)
                    self.impacts.append(row)

        # Rules
        rules_file = self.rules_dir / "inferred_rules.csv"
        if rules_file.exists():
            with open(rules_file) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    self.rules.append(row)

        # Workflows
        wf_file = self.workflows_dir / "workflows.json"
        if wf_file.exists():
            with open(wf_file) as f:
                self.workflows = json.load(f)

        logger.info(f"  ✓ Loaded {len(self.accounts)} accounts")
        logger.info(f"  ✓ Loaded {len(self.transactions)} transactions")
        logger.info(f"  ✓ Loaded {len(self.impacts)} impacts")
        logger.info(f"  ✓ Loaded {len(self.rules)} rules")
        logger.info(f"  ✓ Loaded {len(self.workflows)} workflows")

    def render_index(self):
        """Render dashboard index."""
        logger.info("Rendering index.html...")

        content = f"""
<h1>QB Rule Mining Dashboard</h1>
<div class="meta">Run: {self.run_dir.name}</div>

<div class="nav">
    <a href="accounts-tree.html">Account Hierarchy</a>
    <a href="transactions-list.html">Transactions</a>
    <a href="workflows.html">Workflows</a>
    <a href="rules-review.html">Posting Rules</a>
</div>

<h2>Quick Stats</h2>
<table>
    <tr><th>Metric</th><th>Count</th></tr>
    <tr><td>Accounts</td><td>{len(self.accounts)}</td></tr>
    <tr><td>Transactions</td><td>{len(self.transactions)}</td></tr>
    <tr><td>Account Impacts</td><td>{len(self.impacts)}</td></tr>
    <tr><td>Workflows Detected</td><td>{len(self.workflows)}</td></tr>
    <tr><td>Posting Rules Inferred</td><td>{len(self.rules)}</td></tr>
</table>

<h2>Top Accounts by Impact Count</h2>
{self._render_top_accounts_table()}

<div class="info">
    <strong>Next Steps:</strong>
    <ul style="margin-left: 20px; margin-top: 5px;">
        <li>Review account hierarchy to confirm parent/child relationships</li>
        <li>Examine transaction details to validate posting logic</li>
        <li>Assess workflow patterns against business processes</li>
        <li>Approve or modify inferred posting rules</li>
    </ul>
</div>
"""

        self._write_html("index.html", "QB Rule Mining Dashboard", content)

    def render_accounts_tree(self):
        """Render account hierarchy tree."""
        logger.info("Rendering accounts-tree.html...")

        # Build tree by root account
        roots = {}
        for acc_id, hier in self.account_hierarchy.items():
            root_id = hier['root_id']
            if root_id not in roots:
                roots[root_id] = []
            roots[root_id].append((acc_id, hier))

        tree_html = ""
        for root_id in sorted(roots.keys()):
            root_hier = self.account_hierarchy.get(root_id, {})
            tree_html += f"<div class='impact-tree'>"
            tree_html += f"<div class='root-account'>{root_hier.get('name', root_id)}</div>"

            for acc_id, hier in sorted(roots[root_id], key=lambda x: x[1]['depth']):
                if acc_id != root_id:
                    indent = "&nbsp;" * (hier['depth'] * 4)
                    tree_html += f"<div class='account-row'>{indent}<span class='sub-account'>{hier['name']}</span></div>"

            tree_html += "</div>"

        content = f"""
<h1>Account Hierarchy</h1>
<p class="meta">Showing parent/child relationships and account depth</p>

<h2>Root Accounts & Structure</h2>
{tree_html}

<table>
    <thead><tr><th>Account ID</th><th>Name</th><th>Type</th><th>Parent</th><th>Root</th><th>FQN</th></tr></thead>
    <tbody>
        {"".join(f"<tr><td>{acc_id}</td><td>{hier.get('name')}</td><td>{self.accounts.get(acc_id, {}).get('account_type', '')}</td><td>{hier.get('parent_id', '')}</td><td>{hier.get('root_id')}</td><td style='font-size:11px;'>{hier.get('fqn')}</td></tr>" for acc_id, hier in sorted(self.account_hierarchy.items()))}
    </tbody>
</table>
"""

        self._write_html("accounts-tree.html", "Account Hierarchy", content)

    def render_transactions_list(self):
        """Render transaction list."""
        logger.info("Rendering transactions-list.html...")

        rows = "".join(
            f"""<tr>
                <td><a href="transaction-{txn['txn_id']}.html" style="color:#007acc;text-decoration:none;">{txn['txn_id'][:8]}</a></td>
                <td>{txn['txn_type']}</td>
                <td>{txn['txn_date']}</td>
                <td>{txn['doc_number']}</td>
                <td class='debit'>${float(txn['amount_total']):.2f}</td>
            </tr>"""
            for txn in sorted(self.transactions.values(), key=lambda x: x['txn_date'], reverse=True)
        )

        content = f"""
<h1>Transaction List</h1>
<p class="meta">All transactions in 1-year window</p>

<table>
    <thead><tr><th>TXN ID</th><th>Type</th><th>Date</th><th>Doc #</th><th>Amount</th></tr></thead>
    <tbody>{rows}</tbody>
</table>
"""

        self._write_html("transactions-list.html", "Transactions", content)

    def render_transaction_details(self, txn_id: str):
        """Render individual transaction detail page."""
        txn = self.transactions.get(txn_id)
        if not txn:
            return

        # Get impacts for this transaction
        txn_impacts = [i for i in self.impacts if i['txn_id'] == txn_id]

        # Build posting block
        posting_lines = ""
        total_debit = 0.0
        total_credit = 0.0

        for impact in txn_impacts:
            debit = float(impact['debit_amount'])
            credit = float(impact['credit_amount'])
            total_debit += debit
            total_credit += credit

            debit_str = f"<span class='debit'>${debit:.2f}</span>" if debit > 0 else ""
            credit_str = f"<span class='credit'>${credit:.2f}</span>" if credit > 0 else ""

            posting_lines += f"""
            <div class='posting-line'>
                <span>{impact['account_name']} ({impact['account_id']})</span>
                <span>{debit_str}{credit_str}</span>
            </div>
            """

        posting_lines += f"""
        <div class='posting-line total'>
            <span>TOTAL</span>
            <span><span class='debit'>${total_debit:.2f}</span> / <span class='credit'>${total_credit:.2f}</span></span>
        </div>
        """

        # Account impact tree
        impact_tree = ""
        root_impacts = {}
        for impact in txn_impacts:
            root = impact['root_account_name']
            if root not in root_impacts:
                root_impacts[root] = []
            root_impacts[root].append(impact)

        for root in sorted(root_impacts.keys()):
            impact_tree += f"<div class='impact-tree'>"
            impact_tree += f"<div class='root-account'>{root}</div>"

            for impact in root_impacts[root]:
                parent = impact['parent_account_name']
                account = impact['account_name']
                debit = float(impact['debit_amount'])
                credit = float(impact['credit_amount'])

                impact_tree += f"<div class='account-row'>"
                impact_tree += f"<span class='sub-account'>{parent} → {account}</span>"
                if debit > 0:
                    impact_tree += f" <span class='debit'>${debit:.2f}D</span>"
                if credit > 0:
                    impact_tree += f" <span class='credit'>${credit:.2f}C</span>"
                impact_tree += f"</div>"

            impact_tree += "</div>"

        content = f"""
<a href="transactions-list.html">← Back to List</a>

<h1>Transaction Details</h1>
<div class="meta">TXN ID: {txn['txn_id']}</div>

<h2>Header</h2>
<table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Type</td><td>{txn['txn_type']}</td></tr>
    <tr><td>Date</td><td>{txn['txn_date']}</td></tr>
    <tr><td>Doc Number</td><td>{txn['doc_number']}</td></tr>
    <tr><td>Amount</td><td>${float(txn['amount_total']):.2f}</td></tr>
    <tr><td>Customer/Vendor</td><td>{txn.get('customer_id', txn.get('vendor_id', ''))}</td></tr>
</table>

<h2>Posting Lines</h2>
<div class='posting-block'>
    {posting_lines}
</div>

<h2>Account Impact Summary</h2>
{impact_tree}
"""

        self._write_html(f"transaction-{txn_id}.html", f"Transaction {txn_id[:8]}", content)

    def render_workflows(self):
        """Render workflows summary."""
        logger.info("Rendering workflows.html...")

        rows = "".join(
            f"""<tr>
                <td>{wf['workflow_id']}</td>
                <td>{wf['trigger_type']}</td>
                <td>{wf['doc_sequence']}</td>
                <td>${float(wf['total_amount']):.2f}</td>
                <td>{wf.get('days_to_payment', 0)}</td>
            </tr>"""
            for wf in sorted(self.workflows, key=lambda x: x['trigger_type'])
        )

        content = f"""
<h1>Workflows Detected</h1>
<p class="meta">Document chains and transaction sequences</p>

<table>
    <thead><tr><th>Workflow ID</th><th>Type</th><th>Sequence</th><th>Amount</th><th>Days to Close</th></tr></thead>
    <tbody>{rows}</tbody>
</table>

<h2>Summary by Workflow Type</h2>
{self._render_workflow_summary()}
"""

        self._write_html("workflows.html", "Workflows", content)

    def render_rules_review(self):
        """Render posting rules for review."""
        logger.info("Rendering rules-review.html...")

        rows = "".join(
            f"""<tr>
                <td><strong>{rule['rule_id']}</strong></td>
                <td><code>{rule['trigger_conditions']}</code></td>
                <td>{rule['expected_debits']}</td>
                <td>{rule['expected_credits']}</td>
                <td>{rule['support_count']}</td>
                <td>{float(rule['consistency_pct']):.1f}%</td>
                <td>{float(rule['confidence_score']):.2f}</td>
                <td>{'🔒 Locked' if rule['locked'] == 'true' else '⬜ Review'}</td>
            </tr>"""
            for rule in sorted(self.rules, key=lambda x: x['confidence_score'], reverse=True)
        )

        content = f"""
<h1>Posting Rules Review</h1>
<p class="meta">Inferred rules with approval checklist</p>

<div class="warning">
    <strong>⚠ Action Required:</strong> Review each rule below. Mark as Approved or Rejected.
</div>

<table>
    <thead>
        <tr>
            <th>Rule ID</th>
            <th>Trigger</th>
            <th>Expected Debits</th>
            <th>Expected Credits</th>
            <th>Support</th>
            <th>Consistency</th>
            <th>Confidence</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>{rows}</tbody>
</table>

<h2>Approval Checklist</h2>
<div class="info">
    For each rule:
    <ul style="margin-left: 20px; margin-top: 5px;">
        <li>☐ Trigger condition matches business process</li>
        <li>☐ Expected debits are correct account(s)</li>
        <li>☐ Expected credits are correct account(s)</li>
        <li>☐ Sample transactions validate the pattern</li>
        <li>☐ Consistency % is acceptable (>80% recommended)</li>
        <li>☐ Confidence score is sufficient</li>
        <li>☐ No exceptions that break the rule</li>
    </ul>
</div>
"""

        self._write_html("rules-review.html", "Posting Rules Review", content)

    # ========================================================================
    # Helpers
    # ========================================================================

    def _render_top_accounts_table(self) -> str:
        """Render table of top accounts by impact count."""
        account_impacts = {}
        for impact in self.impacts:
            acc_id = impact['account_id']
            account_impacts[acc_id] = account_impacts.get(acc_id, 0) + 1

        top_10 = sorted(account_impacts.items(), key=lambda x: x[1], reverse=True)[:10]

        rows = "".join(
            f"<tr><td>{acc_id}</td><td>{self.accounts.get(acc_id, {}).get('account_name', '')}</td><td>{count}</td></tr>"
            for acc_id, count in top_10
        )

        return f"<table><thead><tr><th>Account ID</th><th>Name</th><th>Impact Count</th></tr></thead><tbody>{rows}</tbody></table>"

    def _render_workflow_summary(self) -> str:
        """Render workflow type summary."""
        by_type = {}
        for wf in self.workflows:
            wf_type = wf['trigger_type']
            if wf_type not in by_type:
                by_type[wf_type] = {'count': 0, 'amount': 0.0}
            by_type[wf_type]['count'] += 1
            by_type[wf_type]['amount'] += float(wf['total_amount'])

        rows = "".join(
            f"<tr><td>{wf_type}</td><td>{by_type[wf_type]['count']}</td><td>${by_type[wf_type]['amount']:.2f}</td></tr>"
            for wf_type in sorted(by_type.keys())
        )

        return f"<table><thead><tr><th>Workflow Type</th><th>Count</th><th>Total Amount</th></tr></thead><tbody>{rows}</tbody></table>"

    def _write_html(self, filename: str, title: str, content: str):
        """Write HTML file."""
        html = HTML_TEMPLATE.format(
            title=title,
            content=content,
            timestamp=datetime.now().isoformat(timespec='seconds')
        )

        filepath = self.html_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)

        logger.info(f"  ✓ {filename}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python render_html_mockups.py <run_dir>")
        sys.exit(1)

    run_dir = Path(sys.argv[1])

    logger_obj = logging.getLogger(__name__)
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s | %(levelname)s | %(message)s',
        handlers=[
            logging.FileHandler(run_dir / "html_render.log"),
            logging.StreamHandler(sys.stdout)
        ]
    )

    logger_obj.info("=" * 80)
    logger_obj.info("QB HTML RENDERING")
    logger_obj.info(f"Output: {run_dir / 'html'}")
    logger_obj.info("=" * 80)

    renderer = HTMLRenderer(run_dir)

    try:
        renderer.load_data()

        # Render pages
        renderer.render_index()
        renderer.render_accounts_tree()
        renderer.render_transactions_list()
        renderer.render_workflows()
        renderer.render_rules_review()

        # Render transaction detail pages (sample)
        for txn_id in list(renderer.transactions.keys())[:50]:
            renderer.render_transaction_details(txn_id)

        logger_obj.info("\n" + "=" * 80)
        logger_obj.info("HTML RENDERING COMPLETE")
        logger_obj.info(f"Open: {renderer.html_dir / 'index.html'}")
        logger_obj.info("=" * 80)

        logger_obj.info(f"\nNext: python generate_accountant_packet.py {run_dir}")

        return 0

    except Exception as e:
        logger_obj.error(f"HTML rendering failed: {str(e)}")
        import traceback
        logger_obj.error(traceback.format_exc())
        return 1

if __name__ == '__main__':
    import os
    sys.exit(main())
